# SPDX-FileCopyrightText: 2025 MDAD project contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

---
# Default configuration for Matrix version history tracking

# Container identification
matrix_container_prefix: "matrix-"  # Prefix used to identify Matrix containers

# Retention policy configuration
matrix_history_max_entries: 100  # Maximum number of history entries to keep (0 = unlimited)
matrix_history_retention_days: 365  # Number of days to retain history entries (0 = unlimited)

# Display settings
matrix_show_version_summary: true  # Legacy variable - kept for backward compatibility
matrix_version_summary_display: "{{ matrix_show_version_summary | bool }}"  # Primary control variable

# Fact file locations
matrix_versions_fact_file: "matrix_versions.fact"  # Current versions fact file
matrix_history_fact_file: "matrix_version_history.fact"  # Version history fact file

# Table display settings
matrix_table_style_unicode: false  # Set to false for ASCII-only tables (recommended for consistent display)

# Table column width settings (optimized for standard terminal display)
matrix_table_service_width: 30      # Width for service/container name column (fits standard terminals)
matrix_table_version_width: 25      # Width for version columns (shows most version strings clearly)
matrix_table_status_width: 9        # Width for status column

# Version extraction settings
matrix_version_extract_smart: true  # Extract clean version tags (e.g., "synapse:v1.96.1" from full image name)
