# SPDX-FileCopyrightText: 2025 MDAD project contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Test Table Formatting
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Set ASCII table characters
      ansible.builtin.set_fact:
        h_line: "-"
        v_line: "|"
        tl_corner: "+"
        tr_corner: "+"
        bl_corner: "+"
        br_corner: "+"
        t_down: "+"
        t_up: "+"
        t_right: "+"
        t_left: "+"
        cross: "+"
        double_h_line: "="
        double_cross: "+"

    - name: Test table structure
      ansible.builtin.set_fact:
        top_line: "{{ tl_corner }}{{ h_line * 32 }}{{ t_down }}{{ h_line * 32 }}{{ t_down }}{{ h_line * 32 }}{{ t_down }}{{ h_line * 11 }}{{ tr_corner }}"
        header_row: "{{ v_line }} {{ 'SERVICE/CONTAINER' | ljust(30) }} {{ v_line }} {{ 'VERSION BEFORE' | ljust(30) }} {{ v_line }} {{ 'VERSION AFTER' | ljust(30) }} {{ v_line }} {{ 'STATUS' | ljust(9) }} {{ v_line }}"
        header_sep: "{{ t_right }}{{ double_h_line * 32 }}{{ double_cross }}{{ double_h_line * 32 }}{{ double_cross }}{{ double_h_line * 32 }}{{ double_cross }}{{ double_h_line * 11 }}{{ t_left }}"
        data_row: "{{ v_line }} {{ 'service-api' | ljust(30) }} {{ v_line }} {{ 'registry.local/api:v1.95.1' | ljust(30) }} {{ v_line }} {{ 'registry.local/api:v1.96.0' | ljust(30) }} {{ v_line }} {{ 'UPDATED' | ljust(9) }} {{ v_line }}"
        bottom_line: "{{ bl_corner }}{{ h_line * 32 }}{{ t_up }}{{ h_line * 32 }}{{ t_up }}{{ h_line * 32 }}{{ t_up }}{{ h_line * 11 }}{{ br_corner }}"

    - name: Display test table
      ansible.builtin.debug:
        msg: |
          DOCKER SERVICE VERSION CHANGES - TEST

          {{ top_line }}
          {{ header_row }}
          {{ header_sep }}
          {{ data_row }}
          {{ bottom_line }}

          [TEST TABLE FORMATTING]
