---
- name: Test table formatting only
  hosts: localhost
  gather_facts: yes
  vars:
    # Test data
    after_versions:
      "matrix-synapse":
        previous: "-"
        current: "matrixdotorg/synapse:v1.95.1"
        status: "NEW"
      "matrix-postgres": 
        previous: "postgres:15.3-alpine"
        current: "postgres:15.4-alpine"
        status: "UPDATED"
      "matrix-redis":
        previous: "-"
        current: "redis:7.2-alpine" 
        status: "NEW"
    
    # Table settings
    matrix_table_style_unicode: false
    
  tasks:
    - name: Set table characters (ASCII)
      ansible.builtin.set_fact:
        h_line: "-"
        v_line: "|"
        cross: "+"
        t_down: "+"
        t_up: "+"
        t_right: "+"
        t_left: "+"

    - name: Create table header
      ansible.builtin.set_fact:
        top_line: "{{ '+' + ('-' * 32) + '+' + ('-' * 32) + '+' + ('-' * 32) + '+' + ('-' * 11) + '+' }}"
        header_row: "{{ '| ' + (('Service' + ' ' * 30)[:30]) + ' | ' + (('Previous Version' + ' ' * 30)[:30]) + ' | ' + (('Current Version' + ' ' * 30)[:30]) + ' | ' + (('Status' + ' ' * 9)[:9]) + ' |' }}"
        header_sep: "{{ '+' + ('-' * 32) + '+' + ('-' * 32) + '+' + ('-' * 32) + '+' + ('-' * 11) + '+' }}"
        bottom_line: "{{ '+' + ('-' * 32) + '+' + ('-' * 32) + '+' + ('-' * 32) + '+' + ('-' * 11) + '+' }}"

    - name: Initialize table rows
      ansible.builtin.set_fact:
        table_rows: []

    - name: Add table rows
      ansible.builtin.set_fact:
        table_rows: "{{ table_rows + [table_row] }}"
      vars:
        table_row: >-
          {{ v_line + ' ' +
             ((item.key | truncate(30, true)) + ' ' * 30)[:30] + ' ' +
             v_line + ' ' +
             (((item.value.previous | default('-') | string | truncate(30, true)) + ' ' * 30)[:30]) + ' ' +
             v_line + ' ' +
             (((item.value.current | string | truncate(30, true)) + ' ' * 30)[:30]) + ' ' +
             v_line + ' ' +
             ((item.value.status + ' ' * 9)[:9]) + ' ' +
             v_line }}
      loop: "{{ after_versions | dict2items | sort(attribute='key') }}"

    - name: Build complete table as list
      ansible.builtin.set_fact:
        version_summary_table_lines: >-
          {{ ['MATRIX VERSION CHANGES - ' + ansible_date_time.iso8601, ''] +
             [top_line, header_row, header_sep] +
             table_rows +
             [bottom_line, '', 'Total matrix containers: ' + (after_versions | length | string), ''] }}

    - name: Display formatted table
      ansible.builtin.debug:
        msg: "{{ version_summary_table_lines }}"

    - name: Show table_rows structure for debugging
      ansible.builtin.debug:
        var: table_rows