# SPDX-FileCopyrightText: 2025 MDAD project contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

---
# Matrix Version History management playbook
- name: Clear Matrix Version History
  hosts: "{{ target_host | default('matrix_servers') }}"
  gather_facts: true
  vars:
    confirm_clear: "{{ confirm_clear | default('no') }}"
    matrix_history_fact_file: "{{ matrix_history_fact_file | default('matrix_version_history.fact') }}"
  tasks:
    - name: Confirm history clearing
      ansible.builtin.fail:
        msg: "History clearing aborted. Use -e 'confirm_clear=yes' to confirm clearing history."
      when: confirm_clear != 'yes'

    - name: Check if history file exists
      ansible.builtin.stat:
        path: "/etc/ansible/facts.d/{{ matrix_history_fact_file }}"
      register: history_file

    - name: Create backup of history file
      ansible.builtin.copy:
        src: "/etc/ansible/facts.d/{{ matrix_history_fact_file }}"
        dest: "/etc/ansible/facts.d/{{ matrix_history_fact_file }}.backup.{{ ansible_date_time.epoch }}"
        mode: '0644'
        remote_src: true
      become: true
      when: history_file.stat.exists

    - name: Clear version history
      ansible.builtin.file:
        path: "/etc/ansible/facts.d/{{ matrix_history_fact_file }}"
        state: absent
      become: true
      register: clear_result

    - name: Display confirmation message
      ansible.builtin.debug:
        msg: |
          Matrix version history has been cleared successfully.
          Backup saved to: /etc/ansible/facts.d/{{ matrix_history_fact_file }}.backup.{{ ansible_date_time.epoch }}
      when: clear_result.changed and history_file.stat.exists

    - name: Display no history message
      ansible.builtin.debug:
        msg: "No history file found to clear."
      when: not history_file.stat.exists
