---
# Matrix Version History viewing playbook
- name: View Matrix Version History
  hosts: "{{ target_host }}"
  gather_facts: true
  vars:
    view_mode: "{{ view_mode | default('changes') }}"
    service_filter: "{{ service_filter | default('') }}"
    matrix_versions_fact_file: "{{ matrix_versions_fact_file | default('matrix_versions.fact') }}"
    matrix_history_fact_file: "{{ matrix_history_fact_file | default('matrix_version_history.fact') }}"
    matrix_table_style_unicode: "{{ matrix_table_style_unicode | default(true) | bool }}"
  tasks:
    - name: Validate view mode
      ansible.builtin.fail:
        msg: "Invalid view_mode '{{ view_mode }}'. Valid options are 'changes' or 'full'."
      when: view_mode not in ['changes', 'full']
      
    - name: Check if history file exists
      ansible.builtin.stat:
        path: "/etc/ansible/facts.d/{{ matrix_history_fact_file }}"
      register: history_file
      
    - name: Warn if history file missing
      ansible.builtin.debug:
        msg: "Warning: No history file found at /etc/ansible/facts.d/{{ matrix_history_fact_file }}. You may not see any results."
      when: not history_file.stat.exists
    
    - name: Include version history display task
      include_tasks: view_history.yml