---
# Main entry point for the matrix-version-summary role

- name: Ensure facts directory exists
  ansible.builtin.file:
    path: "/etc/ansible/facts.d"
    state: directory
    mode: '0755'
  become: true
  tags: ["matrix-version-summary", "setup"]

# Enable mock mode for testing without Docker
- name: Execute mock mode
  ansible.builtin.import_tasks: mock_mode.yml
  tags: ["matrix-version-summary", "mock"]
  when: matrix_version_summary_mock_mode | default(false) | bool

- name: Display current version summary
  ansible.builtin.import_tasks: display_summary.yml
  tags: ["matrix-version-summary", "version_summary"]
  when: matrix_version_summary_display | default(matrix_show_version_summary) | default(true) | bool

- name: View version history
  ansible.builtin.import_tasks: view_history.yml
  tags: ["matrix-version-summary", "version_history"]
  when: matrix_playbook_show_version_history | default(false) | bool
