---
- name: Display current version summary
  ansible.builtin.import_tasks: display_summary.yml
  tags: ["version_summary", "matrix-version-summary"]
  when: matrix_version_summary_display | default(matrix_show_version_summary) | default(true) | bool

- name: View version history
  ansible.builtin.import_tasks: view_history.yml
  tags: ["version_history"]
  when: matrix_playbook_show_version_history | default(false) | bool
