---
# Process a single service for full history view
# This file is included by view_history.yml when needed

- name: Display service history header for {{ service_name }}
  ansible.builtin.shell: |
    echo "┌─────────────────────────────────────────────────────────────────────────────────┐"
    echo "│ SERVICE: {{ (service_name + (' ' * 69))[:69] }} │"
    echo "│ CURRENT VERSION: {{ ((service_data.version | default('Unknown')) + (' ' * 59))[:59] }} │"
    echo "│ LAST UPDATED: {{ ((service_data.last_updated | default('Unknown')) + (' ' * 62))[:62] }} │"
  changed_when: false

- name: Display service update history
  ansible.builtin.shell: |
    set -o pipefail
    {% if service_data.updates | default([]) | length > 0 %}
    echo "├─────────────────────────────┬───────────────────────┬───────────────────────────┤"
    echo "│ TIMESTAMP                   │ FROM VERSION          │ TO VERSION                │"
    echo "├─────────────────────────────┼───────────────────────┼───────────────────────────┤"
    {% for update in service_data.updates | default([]) %}
    echo "│ {{ (update.timestamp + (' ' * 27))[:27] }} │ {{
      ((update.previous | default('-') | string) + (' ' * 21))[:21] }} │ {{
      ((update.current | string) + (' ' * 25))[:25] }} │"
    {% endfor %}
    {% else %}
    echo "│ No version changes recorded for this service.                                   │"
    {% endif %}
  changed_when: false

- name: Display service history footer
  ansible.builtin.shell: |
    echo "└─────────────────────────────┴───────────────────────┴───────────────────────────┘"
    echo ""
  changed_when: false
