# SPDX-FileCopyrightText: 2025 MDAD project contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

---
# Main entry point for the docker-ansible-summary role

- name: Ensure facts directory exists
  ansible.builtin.file:
    path: "/etc/ansible/facts.d"
    state: directory
    mode: '0755'
  become: true
  tags: ["docker-ansible-summary", "matrix-version-summary", "setup"]

# Enable mock mode for testing without Docker
- name: Execute mock mode
  ansible.builtin.import_tasks: mock_mode.yml
  tags: ["docker-ansible-summary", "matrix-version-summary", "mock"]
  when: docker_summary_mock_mode | default(matrix_version_summary_mock_mode | default(false), true) | bool

- name: Display current version summary
  ansible.builtin.import_tasks: display_summary.yml
  tags: ["docker-ansible-summary", "matrix-version-summary", "version_summary"]
  when: docker_summary_display | default(matrix_version_summary_display | default(matrix_show_version_summary | default(true)), true) | bool

- name: View version history
  ansible.builtin.import_tasks: view_history.yml
  tags: ["docker-ansible-summary", "matrix-version-summary", "version_history"]
  when: docker_summary_show_history | default(matrix_playbook_show_version_history | default(false), true) | bool
